language: python
python:
  - "3.9.7"
env:
  - FLASK_VERSION=2.2.3
install:
  - pip install -U Flask==$FLASK_VERSION
  - pip install codecov
  - pip install pylint
script: 
  - python setup.py install
  - coverage run setup.py install
  - pylint department-app
after_success:
  - coveralls