language: python

python:
  - "3.9.7"
env:
  - FLASK_VERSION=2.2.3
install:
  - pip install -U Flask==$FLASK_VERSION
  - pip install flask-mysqldb
  - pip install codecov
  - pip install pylint
  - pip install coveralls
script: 
  - python setup.py install
  - coverage run setup.py install && coverage html
  - pylint department-app
after_success:
  - coveralls