language: python

python:
  - "3.9.7"
env:
  - FLASK_VERSION=2.2.3
install:
  - pip install -U Flask==$FLASK_VERSION
  - pip install flask-mysqldb
  - pip install codecov
  - pip install pylint
  - pip install coveralls
script: 
  - python setup.py install
  - python /MIGRATE_FOLDER/001_create_categories_schema.py
  - python /MIGRATE_FOLDER/002_create_items_schema.py
  - python /MIGRATE_FOLDER/003_data_init.py
  - coverage run setup.py install && coverage html
  - pylint department-app
after_success:
  - coveralls