language: python
python:
  - "3.9.7"
env:
  - FLASK_VERSION=2.2.3
install:
  - pip install -U Flask==$FLASK_VERSION
  - pip install coveralls
script: 
  - python setup.py test home
  - coverage run --source=home setup.py test home
after_success:
  - coveralls