language: python
python:
  - "3.9.7"
env:
  - FLASK_VERSION=2.2.3
install:
  - pip install -U Flask==$FLASK_VERSION
  - pip install coveralls
script: 
  - coverage run -m pytest tests
  - pylint app_folder
after_success:
  - coveralls